version: "3.7"
services:
  markkubot_dev:
    image: markkubot_dev:latest
    env_file:
      - .env
    depends_on:
      - db
    restart: always
    networks:
      - backend
  db:
    image: postgres
    env_file:
      - .env
    restart: on-failure
    networks:
      - backend
    volumes:
      - data-volume:/data/db

volumes:
  data-volume:

networks:
  backend: