version: "3.0.0"
services:
  markkubot:
    image: kulmajaba/markkubot:3.0.0
    env_file: .env
    depends_on:
    - mongo
  mongo:
    image: mongo:3.6.6
    ports:
      - "27017:27017"
    volumes:
    - data-volume:/data/db
volumes:
  data-volume:
